// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection; the pgbouncer
    // transaction-mode pooler used by DATABASE_URL doesn't support the
    // advisory locks Prisma Migrate relies on. Falls back to DATABASE_URL
    // for plain local Postgres setups that have no separate pooler.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
